[package]
name = "rust-rest-api"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version="1.0.219", features = ["derive"]}
actix-web = "4.11.0"
dotenv = "0.15.0"
env_logger = "0.11.8"
sqlx = { version = "0.8.6", features = ["postgres","runtime-async-std"] }
